CREATE TABLE IF NOT EXISTS `blogs` (
 `id` INT(11) NOT NULL, 
 `title` VARCHAR(32) NOT NULL , 
 `body` text NOT NULL , 
 `delete_flag` INT(1) NULL DEFAULT NULL, 
 `created` DATETIME NOT NULL , 
 `modified` TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

ALTER TABLE `blogs`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `blogs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;